export enum ImageSizes {
  COVER_SMALL = "cover_small",
  COVER_BIG = "cover_big",
  LOGO_MED = "logo_med",
  THUMB = "thumb",
  MICRO = "micro",
  SCREENSHOT_MED = "screenshot_med",
  SCREENSHOT_BIG = "screenshot_big",
  SCREENSHOT_HUGE = "screenshot_huge",
  HD = "720p",
  FHD = "1080p",
  COVER_SMALL_2X = "cover_small_2x",
  COVER_BIG_2X = "cover_big_2x",
  LOGO_MED_2X = "logo_med_2x",
  THUMB_2X = "thumb_2x",
  MICRO_2X = "micro_2x",
  SCREENSHOT_MED_2X = "screenshot_med_2x",
  SCREENSHOT_BIG_2X = "screenshot_big_2x",
  SCREENSHOT_HUGE_2X = "screenshot_huge_2x",
  HD_2X = "720p_2x",
  FHD_2X = "1080p_2x",
}
